name = "GuiggianiRichardsonDuffy"
uuid = "aec3023f-1de0-439c-a184-b65ea860326a"
authors = ["Marc BONNET <marc.bonnet@ensta-paris.fr>", "Luiz FARIA <luiz.faria@ensta-paris.fr>", "Adrien VET <adrien.vet@ensta-paris.fr>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Inti = "fb74042b-437e-4c5b-88cf-d4e2beb394d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ForwardDiff = "1.2.1"
Inti = "0.2.0"
LinearAlgebra = "1.11.0"
Memoization = "0.2.2"
Richardson = "1.4.2"
StaticArrays = "1.9.15"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
