name = "GuiggianiRichardsonDuffy"
uuid = "aec3023f-1de0-439c-a184-b65ea860326a"
authors = ["Marc BONNET <marc.bonnet@ensta-paris.fr>", "Luiz FARIA <luiz.faria@ensta-paris.fr>", "Adrien VET <adrien.vet@ensta-paris.fr>"]
version = "0.1.0"

[deps]
Inti = "fb74042b-437e-4c5b-88cf-d4e2beb394d5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Inti = "0.2.0"
LinearAlgebra = "1.11.0"
Richardson = "1.4.2"
StaticArrays = "1.9.15"
