[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
GuiggianiRichardsonDuffy = "aec3023f-1de0-439c-a184-b65ea860326a"
Inti = "fb74042b-437e-4c5b-88cf-d4e2beb394d5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
