[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GuiggianiRichardsonDuffy = "aec3023f-1de0-439c-a184-b65ea860326a"
Inti = "fb74042b-437e-4c5b-88cf-d4e2beb394d5"
Memoization = "6fafb56a-5788-4b4e-91ca-c0cea6611c73"
Richardson = "708f8203-808e-40c0-ba2d-98a6953ed40d"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"

